apiVersion: v1
data:
  password.txt: UyFCXCpkJHpEc2I9
  username.txt: YWRtaW4=
kind: Secret
metadata:
  creationTimestamp: "2026-06-07T18:30:20Z"
  name: db-user-pass
  namespace: default
  resourceVersion: "52843"
  uid: 25d059d6-8a84-4c08-900c-7be82ec0b337
type: Opaque
